language: ruby

rvm:
  - 1.9.3


env:
  - NUODB_ROOT=/opt/nuodb NUODB_VERSION=1.1.1
  - NUODB_ROOT=/opt/nuodb NUODB_VERSION=1.1
  - NUODB_ROOT=/opt/nuodb NUODB_VERSION=1.0.2
  - NUODB_ROOT=/opt/nuodb NUODB_VERSION=1.0.1

install:
  - gem install bundler
  - gem install thread_safe
  - gem install minitest
  - gem install io-console
  - gem install atomic
  - gem install bigdecimal
  - gem install mocha
  - sudo apt-get update
  - sudo apt-get install libtool libxml2 openssl sqlite
  - sudo apt-get install rbenv
  #- rbenv install 1.9.3-p392
  #- rbenv global 1.9.3-p392
  #- rbenv rehash
  - gem install nuodb
  - gem install activerecord-nuodb-adapter
  - gem install rails -v "=3.2.8"

before_install:
  - wget http://www.nuodb.com/latest/releases/nuodb-${NUODB_VERSION}.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 2
  - sudo chmod 777 active_setup_linux.sh

before_script:
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password baz --verbose debug --archive /var/tmp/nuodb --initialize --force &
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password baz &
  - sleep 2
  - echo "create user cloud password 'user';" | ${NUODB_ROOT}/bin/nuosql test@localhost --user dba --password baz
  - sleep 10

script:
  - ./active_setup_linux.sh
  - cp ~/tmpy/rails-latest/load_paths.rb /home/travis/build/CarlosReyesStoneham/
  - cp /home/travis/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/minitest/autorun.rb /home/travis/.rvm/gems/ruby-1.9.3-p448/gems/activesupport-3.2.14/lib/active_support/testing
  - cp /home/travis/.rvm/gems/ruby-1.9.3-p448/gems/activesupport-3.2.14/lib/active_support/core_ext/logger.rb /home/travis/.rvm/gems/ruby-1.9.3-p448/gems/activesupport-3.2.14/lib/active_support/
  - cp /home/travis/.rvm/gems/ruby-1.9.3-p448/gems/erubis-2.7.0/lib/erubis.rb /home/travis/.rvm/gems/ruby-1.9.3-p448/gems/activesupport-3.2.14/lib/active_support/

  - ARCONN=nuodb ruby -I.:test:/home/travis/.rvm/gems/ruby-1.9.3-p448/gems/ ~/tmpy/rails-latest/activerecord/test/cases/migration_test.rb

after_script:
  - sudo dpkg -r nuodb
